/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int SRBDynamics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int SRBDynamics_alloc_mem(void);
extern "C" int SRBDynamics_init_mem(int mem);
extern "C" void SRBDynamics_free_mem(int mem);
extern "C" int SRBDynamics_checkout(void);
extern "C" void SRBDynamics_release(int mem);
extern "C" void SRBDynamics_incref(void);
extern "C" void SRBDynamics_decref(void);
extern "C" casadi_int SRBDynamics_n_in(void);
extern "C" casadi_int SRBDynamics_n_out(void);
extern "C" casadi_real SRBDynamics_default_in(casadi_int i);
extern "C" const char* SRBDynamics_name_in(casadi_int i);
extern "C" const char* SRBDynamics_name_out(casadi_int i);
extern "C" const casadi_int* SRBDynamics_sparsity_in(casadi_int i);
extern "C" const casadi_int* SRBDynamics_sparsity_out(casadi_int i);
extern "C" int SRBDynamics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define SRBDynamics_SZ_ARG 4
#define SRBDynamics_SZ_RES 1
#define SRBDynamics_SZ_IW 0
#define SRBDynamics_SZ_W 73
extern "C" int SRBDynamicsDerivatives(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int SRBDynamicsDerivatives_alloc_mem(void);
extern "C" int SRBDynamicsDerivatives_init_mem(int mem);
extern "C" void SRBDynamicsDerivatives_free_mem(int mem);
extern "C" int SRBDynamicsDerivatives_checkout(void);
extern "C" void SRBDynamicsDerivatives_release(int mem);
extern "C" void SRBDynamicsDerivatives_incref(void);
extern "C" void SRBDynamicsDerivatives_decref(void);
extern "C" casadi_int SRBDynamicsDerivatives_n_in(void);
extern "C" casadi_int SRBDynamicsDerivatives_n_out(void);
extern "C" casadi_real SRBDynamicsDerivatives_default_in(casadi_int i);
extern "C" const char* SRBDynamicsDerivatives_name_in(casadi_int i);
extern "C" const char* SRBDynamicsDerivatives_name_out(casadi_int i);
extern "C" const casadi_int* SRBDynamicsDerivatives_sparsity_in(casadi_int i);
extern "C" const casadi_int* SRBDynamicsDerivatives_sparsity_out(casadi_int i);
extern "C" int SRBDynamicsDerivatives_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define SRBDynamicsDerivatives_SZ_ARG 4
#define SRBDynamicsDerivatives_SZ_RES 2
#define SRBDynamicsDerivatives_SZ_IW 0
#define SRBDynamicsDerivatives_SZ_W 219
