/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int KinoSRBDynamics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int KinoSRBDynamics_alloc_mem(void);
extern "C" int KinoSRBDynamics_init_mem(int mem);
extern "C" void KinoSRBDynamics_free_mem(int mem);
extern "C" int KinoSRBDynamics_checkout(void);
extern "C" void KinoSRBDynamics_release(int mem);
extern "C" void KinoSRBDynamics_incref(void);
extern "C" void KinoSRBDynamics_decref(void);
extern "C" casadi_int KinoSRBDynamics_n_in(void);
extern "C" casadi_int KinoSRBDynamics_n_out(void);
extern "C" casadi_real KinoSRBDynamics_default_in(casadi_int i);
extern "C" const char* KinoSRBDynamics_name_in(casadi_int i);
extern "C" const char* KinoSRBDynamics_name_out(casadi_int i);
extern "C" const casadi_int* KinoSRBDynamics_sparsity_in(casadi_int i);
extern "C" const casadi_int* KinoSRBDynamics_sparsity_out(casadi_int i);
extern "C" int KinoSRBDynamics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define KinoSRBDynamics_SZ_ARG 3
#define KinoSRBDynamics_SZ_RES 1
#define KinoSRBDynamics_SZ_IW 0
#define KinoSRBDynamics_SZ_W 60
extern "C" int KinoSRBOutput(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int KinoSRBOutput_alloc_mem(void);
extern "C" int KinoSRBOutput_init_mem(int mem);
extern "C" void KinoSRBOutput_free_mem(int mem);
extern "C" int KinoSRBOutput_checkout(void);
extern "C" void KinoSRBOutput_release(int mem);
extern "C" void KinoSRBOutput_incref(void);
extern "C" void KinoSRBOutput_decref(void);
extern "C" casadi_int KinoSRBOutput_n_in(void);
extern "C" casadi_int KinoSRBOutput_n_out(void);
extern "C" casadi_real KinoSRBOutput_default_in(casadi_int i);
extern "C" const char* KinoSRBOutput_name_in(casadi_int i);
extern "C" const char* KinoSRBOutput_name_out(casadi_int i);
extern "C" const casadi_int* KinoSRBOutput_sparsity_in(casadi_int i);
extern "C" const casadi_int* KinoSRBOutput_sparsity_out(casadi_int i);
extern "C" int KinoSRBOutput_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define KinoSRBOutput_SZ_ARG 1
#define KinoSRBOutput_SZ_RES 1
#define KinoSRBOutput_SZ_IW 0
#define KinoSRBOutput_SZ_W 23
extern "C" int KinoSRBDynamicsDerivatives(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int KinoSRBDynamicsDerivatives_alloc_mem(void);
extern "C" int KinoSRBDynamicsDerivatives_init_mem(int mem);
extern "C" void KinoSRBDynamicsDerivatives_free_mem(int mem);
extern "C" int KinoSRBDynamicsDerivatives_checkout(void);
extern "C" void KinoSRBDynamicsDerivatives_release(int mem);
extern "C" void KinoSRBDynamicsDerivatives_incref(void);
extern "C" void KinoSRBDynamicsDerivatives_decref(void);
extern "C" casadi_int KinoSRBDynamicsDerivatives_n_in(void);
extern "C" casadi_int KinoSRBDynamicsDerivatives_n_out(void);
extern "C" casadi_real KinoSRBDynamicsDerivatives_default_in(casadi_int i);
extern "C" const char* KinoSRBDynamicsDerivatives_name_in(casadi_int i);
extern "C" const char* KinoSRBDynamicsDerivatives_name_out(casadi_int i);
extern "C" const casadi_int* KinoSRBDynamicsDerivatives_sparsity_in(casadi_int i);
extern "C" const casadi_int* KinoSRBDynamicsDerivatives_sparsity_out(casadi_int i);
extern "C" int KinoSRBDynamicsDerivatives_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define KinoSRBDynamicsDerivatives_SZ_ARG 3
#define KinoSRBDynamicsDerivatives_SZ_RES 4
#define KinoSRBDynamicsDerivatives_SZ_IW 0
#define KinoSRBDynamicsDerivatives_SZ_W 210
extern "C" int KinoSRBCMatrix(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int KinoSRBCMatrix_alloc_mem(void);
extern "C" int KinoSRBCMatrix_init_mem(int mem);
extern "C" void KinoSRBCMatrix_free_mem(int mem);
extern "C" int KinoSRBCMatrix_checkout(void);
extern "C" void KinoSRBCMatrix_release(int mem);
extern "C" void KinoSRBCMatrix_incref(void);
extern "C" void KinoSRBCMatrix_decref(void);
extern "C" casadi_int KinoSRBCMatrix_n_in(void);
extern "C" casadi_int KinoSRBCMatrix_n_out(void);
extern "C" casadi_real KinoSRBCMatrix_default_in(casadi_int i);
extern "C" const char* KinoSRBCMatrix_name_in(casadi_int i);
extern "C" const char* KinoSRBCMatrix_name_out(casadi_int i);
extern "C" const casadi_int* KinoSRBCMatrix_sparsity_in(casadi_int i);
extern "C" const casadi_int* KinoSRBCMatrix_sparsity_out(casadi_int i);
extern "C" int KinoSRBCMatrix_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define KinoSRBCMatrix_SZ_ARG 1
#define KinoSRBCMatrix_SZ_RES 1
#define KinoSRBCMatrix_SZ_IW 0
#define KinoSRBCMatrix_SZ_W 74
extern "C" int KSRBRunningCost(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int KSRBRunningCost_alloc_mem(void);
extern "C" int KSRBRunningCost_init_mem(int mem);
extern "C" void KSRBRunningCost_free_mem(int mem);
extern "C" int KSRBRunningCost_checkout(void);
extern "C" void KSRBRunningCost_release(int mem);
extern "C" void KSRBRunningCost_incref(void);
extern "C" void KSRBRunningCost_decref(void);
extern "C" casadi_int KSRBRunningCost_n_in(void);
extern "C" casadi_int KSRBRunningCost_n_out(void);
extern "C" casadi_real KSRBRunningCost_default_in(casadi_int i);
extern "C" const char* KSRBRunningCost_name_in(casadi_int i);
extern "C" const char* KSRBRunningCost_name_out(casadi_int i);
extern "C" const casadi_int* KSRBRunningCost_sparsity_in(casadi_int i);
extern "C" const casadi_int* KSRBRunningCost_sparsity_out(casadi_int i);
extern "C" int KSRBRunningCost_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define KSRBRunningCost_SZ_ARG 8
#define KSRBRunningCost_SZ_RES 1
#define KSRBRunningCost_SZ_IW 0
#define KSRBRunningCost_SZ_W 37
extern "C" int KSRBRunningCostDev(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int KSRBRunningCostDev_alloc_mem(void);
extern "C" int KSRBRunningCostDev_init_mem(int mem);
extern "C" void KSRBRunningCostDev_free_mem(int mem);
extern "C" int KSRBRunningCostDev_checkout(void);
extern "C" void KSRBRunningCostDev_release(int mem);
extern "C" void KSRBRunningCostDev_incref(void);
extern "C" void KSRBRunningCostDev_decref(void);
extern "C" casadi_int KSRBRunningCostDev_n_in(void);
extern "C" casadi_int KSRBRunningCostDev_n_out(void);
extern "C" casadi_real KSRBRunningCostDev_default_in(casadi_int i);
extern "C" const char* KSRBRunningCostDev_name_in(casadi_int i);
extern "C" const char* KSRBRunningCostDev_name_out(casadi_int i);
extern "C" const casadi_int* KSRBRunningCostDev_sparsity_in(casadi_int i);
extern "C" const casadi_int* KSRBRunningCostDev_sparsity_out(casadi_int i);
extern "C" int KSRBRunningCostDev_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define KSRBRunningCostDev_SZ_ARG 8
#define KSRBRunningCostDev_SZ_RES 7
#define KSRBRunningCostDev_SZ_IW 0
#define KSRBRunningCostDev_SZ_W 179
extern "C" int KSRBTerminalCost(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int KSRBTerminalCost_alloc_mem(void);
extern "C" int KSRBTerminalCost_init_mem(int mem);
extern "C" void KSRBTerminalCost_free_mem(int mem);
extern "C" int KSRBTerminalCost_checkout(void);
extern "C" void KSRBTerminalCost_release(int mem);
extern "C" void KSRBTerminalCost_incref(void);
extern "C" void KSRBTerminalCost_decref(void);
extern "C" casadi_int KSRBTerminalCost_n_in(void);
extern "C" casadi_int KSRBTerminalCost_n_out(void);
extern "C" casadi_real KSRBTerminalCost_default_in(casadi_int i);
extern "C" const char* KSRBTerminalCost_name_in(casadi_int i);
extern "C" const char* KSRBTerminalCost_name_out(casadi_int i);
extern "C" const casadi_int* KSRBTerminalCost_sparsity_in(casadi_int i);
extern "C" const casadi_int* KSRBTerminalCost_sparsity_out(casadi_int i);
extern "C" int KSRBTerminalCost_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define KSRBTerminalCost_SZ_ARG 5
#define KSRBTerminalCost_SZ_RES 1
#define KSRBTerminalCost_SZ_IW 0
#define KSRBTerminalCost_SZ_W 28
extern "C" int KSRBTerminalCostDev(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int KSRBTerminalCostDev_alloc_mem(void);
extern "C" int KSRBTerminalCostDev_init_mem(int mem);
extern "C" void KSRBTerminalCostDev_free_mem(int mem);
extern "C" int KSRBTerminalCostDev_checkout(void);
extern "C" void KSRBTerminalCostDev_release(int mem);
extern "C" void KSRBTerminalCostDev_incref(void);
extern "C" void KSRBTerminalCostDev_decref(void);
extern "C" casadi_int KSRBTerminalCostDev_n_in(void);
extern "C" casadi_int KSRBTerminalCostDev_n_out(void);
extern "C" casadi_real KSRBTerminalCostDev_default_in(casadi_int i);
extern "C" const char* KSRBTerminalCostDev_name_in(casadi_int i);
extern "C" const char* KSRBTerminalCostDev_name_out(casadi_int i);
extern "C" const casadi_int* KSRBTerminalCostDev_sparsity_in(casadi_int i);
extern "C" const casadi_int* KSRBTerminalCostDev_sparsity_out(casadi_int i);
extern "C" int KSRBTerminalCostDev_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define KSRBTerminalCostDev_SZ_ARG 5
#define KSRBTerminalCostDev_SZ_RES 2
#define KSRBTerminalCostDev_SZ_IW 0
#define KSRBTerminalCostDev_SZ_W 117
