/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int footVelPartialDq(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int footVelPartialDq_alloc_mem(void);
extern "C" int footVelPartialDq_init_mem(int mem);
extern "C" void footVelPartialDq_free_mem(int mem);
extern "C" int footVelPartialDq_checkout(void);
extern "C" void footVelPartialDq_release(int mem);
extern "C" void footVelPartialDq_incref(void);
extern "C" void footVelPartialDq_decref(void);
extern "C" casadi_int footVelPartialDq_n_in(void);
extern "C" casadi_int footVelPartialDq_n_out(void);
extern "C" casadi_real footVelPartialDq_default_in(casadi_int i);
extern "C" const char* footVelPartialDq_name_in(casadi_int i);
extern "C" const char* footVelPartialDq_name_out(casadi_int i);
extern "C" const casadi_int* footVelPartialDq_sparsity_in(casadi_int i);
extern "C" const casadi_int* footVelPartialDq_sparsity_out(casadi_int i);
extern "C" int footVelPartialDq_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define footVelPartialDq_SZ_ARG 2
#define footVelPartialDq_SZ_RES 4
#define footVelPartialDq_SZ_IW 0
#define footVelPartialDq_SZ_W 150
extern "C" int footAccPartialDq(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int footAccPartialDq_alloc_mem(void);
extern "C" int footAccPartialDq_init_mem(int mem);
extern "C" void footAccPartialDq_free_mem(int mem);
extern "C" int footAccPartialDq_checkout(void);
extern "C" void footAccPartialDq_release(int mem);
extern "C" void footAccPartialDq_incref(void);
extern "C" void footAccPartialDq_decref(void);
extern "C" casadi_int footAccPartialDq_n_in(void);
extern "C" casadi_int footAccPartialDq_n_out(void);
extern "C" casadi_real footAccPartialDq_default_in(casadi_int i);
extern "C" const char* footAccPartialDq_name_in(casadi_int i);
extern "C" const char* footAccPartialDq_name_out(casadi_int i);
extern "C" const casadi_int* footAccPartialDq_sparsity_in(casadi_int i);
extern "C" const casadi_int* footAccPartialDq_sparsity_out(casadi_int i);
extern "C" int footAccPartialDq_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define footAccPartialDq_SZ_ARG 3
#define footAccPartialDq_SZ_RES 4
#define footAccPartialDq_SZ_IW 0
#define footAccPartialDq_SZ_W 499
extern "C" int footAccPartialDv(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int footAccPartialDv_alloc_mem(void);
extern "C" int footAccPartialDv_init_mem(int mem);
extern "C" void footAccPartialDv_free_mem(int mem);
extern "C" int footAccPartialDv_checkout(void);
extern "C" void footAccPartialDv_release(int mem);
extern "C" void footAccPartialDv_incref(void);
extern "C" void footAccPartialDv_decref(void);
extern "C" casadi_int footAccPartialDv_n_in(void);
extern "C" casadi_int footAccPartialDv_n_out(void);
extern "C" casadi_real footAccPartialDv_default_in(casadi_int i);
extern "C" const char* footAccPartialDv_name_in(casadi_int i);
extern "C" const char* footAccPartialDv_name_out(casadi_int i);
extern "C" const casadi_int* footAccPartialDv_sparsity_in(casadi_int i);
extern "C" const casadi_int* footAccPartialDv_sparsity_out(casadi_int i);
extern "C" int footAccPartialDv_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define footAccPartialDv_SZ_ARG 3
#define footAccPartialDv_SZ_RES 4
#define footAccPartialDv_SZ_IW 0
#define footAccPartialDv_SZ_W 225
extern "C" int footForcePartialDq(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int footForcePartialDq_alloc_mem(void);
extern "C" int footForcePartialDq_init_mem(int mem);
extern "C" void footForcePartialDq_free_mem(int mem);
extern "C" int footForcePartialDq_checkout(void);
extern "C" void footForcePartialDq_release(int mem);
extern "C" void footForcePartialDq_incref(void);
extern "C" void footForcePartialDq_decref(void);
extern "C" casadi_int footForcePartialDq_n_in(void);
extern "C" casadi_int footForcePartialDq_n_out(void);
extern "C" casadi_real footForcePartialDq_default_in(casadi_int i);
extern "C" const char* footForcePartialDq_name_in(casadi_int i);
extern "C" const char* footForcePartialDq_name_out(casadi_int i);
extern "C" const casadi_int* footForcePartialDq_sparsity_in(casadi_int i);
extern "C" const casadi_int* footForcePartialDq_sparsity_out(casadi_int i);
extern "C" int footForcePartialDq_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define footForcePartialDq_SZ_ARG 2
#define footForcePartialDq_SZ_RES 4
#define footForcePartialDq_SZ_IW 0
#define footForcePartialDq_SZ_W 144
